// src/App.vue
<script setup>
import HelloWorld from './views/HelloWorld.vue'
</script>

<template>
  <div>
    <a href="https://vitejs.dev" target="_blank">
      <img src="https://i.imgur.com/0E7bXw6.png" class="logo" alt="Vite logo" />
    </a>
  </div>

  <h2>Kallery Vue App </h2>
<!--   <router-view></router-view> -->
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>

// kallery-react/src/App.js
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src="https://i.imgur.com/gzlm4nU.png" className="App-logo" alt="logo" />
        <p>
          Kallery React App
        </p>
      </header>
    </div>
  );
}

export default App;
